### ISSUE TITLE
MapViewActivity for Products

### ISSUE THREAD

**Issue by DeepakSumo** [deborshisaha/ModaRenta#22]
* [x] clicking on the map icon on toolbar flips to the map view
* [x] show the markers for each product
* [x] banner at the bottom that shows selected marker
* [ ] banner shows square image (rounded corners), Product Title and $ amount
* [x] clicking on the banner takes to ProductDetailView

**Comment by DeepakSumo** [comment]
@rakheegupta @deborshisaha

**Comment by rakheegupta** [comment]
IMAGE NOT SHOWN YET
AMOUNT NEEDS SYNC WITH MODEL
