### ISSUE TITLE
HomeActivity ListView

### ISSUE THREAD

**Issue by DeepakSumo** [deborshisaha/ModaRenta#23]
* [x] clicking on the item takes to ProductDetailView
* [x] On FAB click take the user to login page if user is not logged in. After that redirect to Products form.
* [x] Fetch sorted results for home activity list.

**Comment by DeepakSumo** [comment]
@deborshisaha @rakheegupta

**Comment by rakheegupta** [comment]
"clicking on the item takes to ProductDetailView" this already works

**Comment by DeepakSumo** [comment]
@rakheegupta I meant from the mapview banner. I know it works from the listview

**Comment by rakheegupta** [comment]
ok.. @DeepakSumo 
marker on the app currently takes the user to detail view

**Comment by DeepakSumo** [comment]
@rakheegupta I couldn't see the banner or markers in the mapview.

**Comment by rakheegupta** [comment]
Try zooming out to see fb hq ....should be around thr

Thanks,
Rakhee

On Mar 15, 2016, at 12:19 AM, Deepak Barge <notifications@github.com<mailto:notifications@github.com>> wrote:


@rakheegupta<https://github.com/rakheegupta> I couldn't see the banner or markers in the mapview.

-

**Comment by rakheegupta** [comment]
Or change the location to ur current location in getrandomlocation method and then run the app

Thanks,
Rakhee

On Mar 15, 2016, at 12:19 AM, Deepak Barge <notifications@github.com<mailto:notifications@github.com>> wrote:


@rakheegupta<https://github.com/rakheegupta> I couldn't see the banner or markers in the mapview.

-

**Comment by DeepakSumo** [comment]
@deborshisaha Looks like this issue has all the tasks done. Closing it
