### ISSUE TITLE
Data models

### ISSUE THREAD

**Issue by DeepakSumo** [deborshisaha/ModaRenta#25]
* [x] Finalize any datamodels/ new columns 
* [x] Verify the data models on parse, USER, ADDRESS and PRODUCT work well together.
* [x] ADDRESS (Location specifically for 03/16) is not getting populated with the product
* [x] Add new column ratingvalue [1-5] to the PRODUCT model in parse

**Comment by DeepakSumo** [comment]
@deborshisaha @rakheegupta

**Comment by rakheegupta** [comment]
i am sending random address near fb hq for evry product being added, we need some sort of address as input from the  product form page if we want user desired address @DeepakSumo  @deborshisaha
