### ISSUE TITLE
Layout details page as per the image attached

### ISSUE THREAD

**Issue by deborshisaha** [deborshisaha/ModaRenta#43]
DO NOT INCLUDE Similar items

![finalsprintdetailspage](https://cloud.githubusercontent.com/assets/389979/13864553/856e5e98-ec5f-11e5-8754-63d390562c8c.png)

**Comment by DeepakSumo** [comment]
* [ ] Increase the map height
* [ ] Add Skype and other icons

**Comment by deborshisaha** [comment]
Closing issue
